// $Id: errorExclaim.xpm.hh 1472 2007-01-01 02:47:59Z flaterco $
/* XPM */
static char *errorExclaimXPM[] = {
/* width height ncolors chars_per_pixel */
"64 59 201 2",
/* colors */
"   c #000000",
" . c #1B1B00",
" X c #363600",
" o c #515100",
" O c #6C6C00",
" + c #D8D800",
" @ c #F3F300",
" # c #070700",
" $ c #222200",
" % c #737300",
" & c #8E8E00",
" * c #A9A900",
" = c #C4C400",
" - c #FAFA00",
" ; c #0E0E00",
" : c #292900",
" > c #444400",
" , c #5F5F00",
" < c #B0B000",
" 1 c #CBCB00",
" 2 c #E6E600",
" 3 c #151500",
" 4 c #303000",
" 5 c #666600",
" 6 c #818100",
" 7 c #9C9C00",
" 8 c #B7B700",
" 9 c #D2D200",
" 0 c #EDED00",
" q c #010100",
" w c #1C1C00",
" e c #6D6D00",
" r c #888800",
" t c #D9D900",
" y c #F4F400",
" u c #080800",
" i c #3E3E00",
" p c #595900",
" a c #8F8F00",
" s c #AAAA00",
" d c #C5C500",
" f c #E0E000",
" g c #FBFB00",
" h c #0F0F00",
" j c #454500",
" k c #606000",
" l c #7B7B00",
" z c #E7E700",
" x c #161600",
" c c #313100",
" v c #828200",
" b c #9D9D00",
" n c #B8B800",
" m c #D3D300",
" M c #EEEE00",
" N c #020200",
" B c #383800",
" V c #535300",
" C c #6E6E00",
" Z c #898900",
" A c #A4A400",
" S c #BFBF00",
" D c #DADA00",
" F c #F5F500",
" G c #090900",
" H c #242400",
" J c #3F3F00",
" K c #5A5A00",
" L c #757500",
" P c #ABAB00",
" I c #C6C600",
" U c #E1E100",
" Y c #FCFC00",
" T c #101000",
" R c #2B2B00",
" E c #616100",
" W c #7C7C00",
" Q c #979700",
" ! c #B2B200",
" ~ c #CDCD00",
" ^ c #E8E800",
" / c #171700",
" ( c #4D4D00",
" ) c #838300",
" _ c #B9B900",
" ` c #D4D400",
" ' c #EFEF00",
" ] c #030300",
" [ c #1E1E00",
" { c #393900",
" } c #545400",
" | c #6F6F00",
".  c #8A8A00",
".. c #C0C000",
".X c #DBDB00",
".o c #F6F600",
".O c #0A0A00",
".+ c #252500",
".@ c #404000",
".# c #767600",
".$ c #919100",
".% c #C7C700",
".& c #E2E200",
".* c #FDFD00",
".= c #111100",
".- c #2C2C00",
".; c #474700",
".: c #B3B300",
".> c #E9E900",
"., c #181800",
".< c #4E4E00",
".1 c #696900",
".2 c #848400",
".3 c #BABA00",
".4 c #D5D500",
".5 c #F0F000",
".6 c #040400",
".7 c #1F1F00",
".8 c #8B8B00",
".9 c #A6A600",
".0 c #C1C100",
".q c #DCDC00",
".w c #0B0B00",
".e c #262600",
".r c #414100",
".t c #5C5C00",
".y c #777700",
".u c #929200",
".i c #ADAD00",
".p c #C8C800",
".a c #E3E300",
".s c #FEFE00",
".d c #121200",
".f c #2D2D00",
".g c #484800",
".h c #636300",
".j c #7E7E00",
".k c #CFCF00",
".l c #EAEA00",
".z c #191900",
".x c #343400",
".c c #4F4F00",
".v c #6A6A00",
".b c #858500",
".n c #A0A000",
".m c #BBBB00",
".M c #F1F100",
".N c #050500",
".B c #202000",
".V c #3B3B00",
".C c #565600",
".Z c #C2C200",
".A c #F8F800",
".S c #0C0C00",
".D c #272700",
".F c #424200",
".G c #5D5D00",
".H c #787800",
".J c #939300",
".K c #C9C900",
".L c #E4E400",
".P c #FFFF00",
".I c #131300",
".U c #2E2E00",
".Y c #494900",
".T c #646400",
".R c #7F7F00",
".E c #9A9A00",
".W c #D0D000",
".Q c #EBEB00",
".! c #1A1A00",
".~ c #353500",
".^ c #505000",
"./ c #868600",
".( c #BCBC00",
".) c #D7D700",
"._ c #F2F200",
".` c #060600",
".' c #212100",
".] c #3C3C00",
".[ c #575700",
".{ c #727200",
".} c #8D8D00",
".| c #DEDE00",
"X  c #F9F900",
"X. c #0D0D00",
"XX c #282800",
"Xo c #797900",
"XO c #949400",
"X+ c #AFAF00",
"X@ c #CACA00",
"X# c #E5E500",
"X$ c #141400",
"X% c #4A4A00",
"X& c #656500",
"X* c #808000",
"X= c #9B9B00",
"X- c #B6B600",
"X; c #D1D100",
"X: c #ECEC00",
"X> c None",
/* pixels */
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P < , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ,.i.P.P.P.P",
".P.P.P.P.a G                                                                                                         u U.P.P.P.P",
".P.P.P.P.P.{    .T e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e eX&     C.P.P.P.P.P",
".P.P.P.P.P.>X.  .8.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P a  .w z.P.P.P.P.P",
".P.P.P.P.P.P l  X$._.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P @ /  .y.P.P.P.P.P.P",
".P.P.P.P.P.P M.=   v.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P./   hX:.P.P.P.P.P.P",
".P.P.P.P.P.P.P.2   T 0.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P '.d   6.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P @ 3  Xo.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P W  .I.M.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.}  .S ^.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P @ 8X-._.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.lX.  . .P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.o .   |.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P m.z     3.K.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P %  .z F.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P Q   u.&.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.F        .U.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.PX# G  .J.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.PX  $   5.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.s.S          .A.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.v  .7.A.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.n  .N.q.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P T        .6 -.P.P.P.P.P.P.P.P.P.P.P.P.P.P.|.`   7.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P YXX  .G.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.U         $.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P E  .e g.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P *   ].4.P.P.P.P.P.P.P.P.P.P.P.P.P.P K         }.P.P.P.P.P.P.P.P.P.P.P.P.P.P +.6  .9.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.* 4   }.P.P.P.P.P.P.P.P.P.P.P.P.P.P.}        .}.P.P.P.P.P.P.P.P.P.P.P.P.P.P.[  .f.*.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P !   q ~.P.P.P.P.P.P.P.P.P.P.P.P.P I        .K.P.P.P.P.P.P.P.P.P.P.P.P.P.W N  X+.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.s B  X%.P.P.P.P.P.P.P.P.P.P.P.P.PX .O     ; g.P.P.P.P.P.P.P.P.P.P.P.P.P.<  .~.s.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.m     d.P.P.P.P.P.P.P.P.P.P.P.P.P.@    .Y.P.P.P.P.P.P.P.P.P.P.P.P.P.p q   n.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.r  .F.P.P.P.P.P.P.P.P.P.P.P.P.P W     Z.P.P.P.P.P.P.P.P.P.P.P.P.P j   i.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P =    .(.P.P.P.P.P.P.P.P.P.P.P.P.3    .K.P.P.P.P.P.P.P.P.P.P.P.P..    .0.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.PX%   {.s.P.P.P.P.P.P.P.P.P.P.P.5 N.w -.P.P.P.P.P.P.P.P.P.P.P.P.]  .;.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P ~ q  .:.P.P.P.P.P.P.P.P.P.P.P.P R B.P.P.P.P.P.P.P.P.P.P.P.P 8   qX@.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P V   c.*.P.P.P.P.P.P.P.P.P.P.P.t E.P.P.P.P.P.P.P.P.P.P.P.s.x  .^.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P ` ]   s.P.P.P.P.P.P.P.P.P.P.PX* 6.P.P.P.P.P.P.P.P.P.P.P.i   N 9.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.t   : Y.P.P.P.P.P.P.P.P.P.P P *.P.P.P.P.P.P.P.P.P.P Y.-   p.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.X.N  .n.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P A  .6 t.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P 5   $X .P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P -.+  .h.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.& u   Q.P.P.P.P.P.P.P.P.) )./.|.P.P.P.P.P.P.P.PX=   # f.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P |   w.o.P.P.P.P.P.P n.`    .w.%.P.P.P.P.P.P.A [   O.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P z.S   &.P.P.P.P.P.P.f        .r.P.P.P.P.P.P.u  .O 2.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.H   x @.P.P.P.P.P.S        .B.P.P.P.P.P y.,   L.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P 0 T  .b.P.P.P.P.P.V        .c.P.P.P.P.P r   ;.Q.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P v  .= '.P.P.P.PX;.,    .'.q.P.P.P.P.M.I  .j.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.MX$   l.P.P.P.P.P.M <.: F.P.P.P.P.P.R  .I.5.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.8  X..l.P.P.P.P.P.P.P.P.P.P.P.PX: ;   r.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P F.!  .{.P.P.P.P.P.P.P.P.P.P.P.P.#  ., y.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.PXO   G.L.P.P.P.P.P.P.P.P.P.P 2.w  .$.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.PX .B  .1.P.P.P.P.P.P.P.P.P.P e   [.A.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P b  .`.|.P.P.P.P.P.P.P.P f #  .E.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P g.D   k.P.P.P.P.P.P.P.P.h   H -.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.9  .6.).P.P.P.P.P.P D.N   A.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.*.U  .C.P.P.P.P.P.P K  .- Y.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P <   N.k.P.P.P.P 9 ]  .i.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.s X   (.P.P.P.P o  .x.s.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P _   q.%.P.P 1 q  X-.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P J   >.P.P.g  .].s.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.Z     S.Z     S.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.;  .V J   j.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.PX@ q     q.p.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P o    .<.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P 9 N N.W.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P K.[.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P D +.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P",
".P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P"
};

// Cleanup2006 Exempt
