// $Id: icon_48x48_3color.xpm.hh 1474 2007-01-01 02:49:40Z flaterco $
/* XPM */
static char *icon_48x48_3color[] = {
/* width height ncolors chars_per_pixel */
"48 48 4 1",
/* colors */
"  c black",
". c sky blue",
"X c blue",
"o c None",
/* pixels */
"................................................",
"................................................",
"........... ... .      . ...... ................",
"............ . ..... .......... ................",
"............ . ..... ... ...    ...   ..........",
"............. ...... ... .. ... .. ... .........",
"............  ...... ... .. ... ..     .........",
"............ . ..... ... .. ... .. .............",
"........... ... .... ... .. ... .. .............",
"........... ... .... ... ...    ...    .........",
"................................................",
"................................................",
"................................................",
"...............................................X",
"............................................XXXX",
"...........................................XXXXX",
".........................................XXXXXXX",
"........................................XXXXXXXX",
".......................................XXXXXXXXX",
"......................................XXXXXXXXXX",
".....................................XXXXXXXXXXX",
"................................ ...XXXXXXXXXXXX",
"................................ ..XXXXXXXXXXXXX",
"................................ .XXXXXXXXXXXXXX",
"................................ XXXXXXXXXXXXXXX",
"............................         XXXXXXXXXXX",
"...............................X XXXXXXXXXXXXXXX",
"..... .........................X XXXXXXXXXXXXXXX",
"....  ........................XX XXXXXXXXXXXXXXX",
"... . .......................XXXXXXXXXXXXXXXXXXX",
"..... ..........  . ........XXXXXXXXXXXXXXXXXXXX",
"..... .......... . . .......XXXXXXXXXXXXXXXXXXXX",
"..... .......... . . ....  XXXXXXXXXXXXXXXXXXXXX",
"..... .......... . . .....XXXXXXXXXXXXXXXXXXXXXX",
"..... .......... . . .....XXXXXXXXXXXXXXXXXXXXXX",
"...     ........ ... ....XXXXXXXXXXXXXXXXXXXXXXX",
"........................XXXXXXXXXXXXXXXXXXXXXXXX",
".......................XXXXXXXXXXXXXXXXXXXXXXXXX",
".......................XXXXXXXXXXXXXXXXXXXXXXXXX",
"......................XXXXXXXXXXXXXXXXXXXXXXXXXX",
".....................XXXXXXXXXXXXXXXXXXXXXXXXXXX",
".....................XXXXXXXXXXXXXXXXXXXXXXXXXXX",
"....................XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"...................XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"..................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"..................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
".................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};

// Cleanup2006 Exempt
